version: "3.8"
services:
  api:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: words
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
volumes:
  db-data: